# Resolution of our program
resolution_1 = 1000
resolution_2 = 1000

# Scaling size for mercator - doesn't really matter
merc_scaling_size_1 = 1000
merc_scaling_size_2 = 1000

# Chart Path
chart_directory = "./src/charts/"
# Coordinates that relate to the top left and bottom right of our screen
top_left_1 = -87.3
top_left_2 = 30.45
bottom_right_1 = -87.230556
bottom_right_2 = 30.380556

# Layer information
# note we can map colors like color = [r, g, b] or [r, g, b, a]
layers = ['LNDARE', 'SEAARE', 'DEPARE', 'DEPCNT']

[SEAARE]
color = "blue"
[LNDARE]
color= "green"
[DEPARE]
color = "blue"
[DEPCNT]
color = 'cyan'

