# Resolution of our program
# 3840x2400
resolution_1 = 3840
resolution_2 = 2400

# Scaling size for mercator - doesn't really matter
merc_scaling_size_1 = 3840
merc_scaling_size_2 = 2400

# Chart Path
chart_directory = "./src/charts/"
# Coordinates that relate to the top left and bottom right of our screen
top_left_1 = -87.63
top_left_2 = 30.65
bottom_right_1 = -85.76
bottom_right_2 = 30.1

# Layer information
# note we can map colors like color = [r, g, b] or [r, g, b, a]
layers = ['LNDARE', 'SEAARE', 'DEPARE']
#layers = ['SEAARE']

[SEAARE]
color = "blue"
[LNDARE]
color= "green"
[DEPARE]
color = "blue"
[DEPCNT]
color = 'cyan'

